spring.application.name=reciclagem

spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=RM560021
spring.datasource.password=040803

spring.flyway.baselineOnMigrate=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.show-sql=true


spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

server.error.include-stacktrace=never
app.alertas.limiteKg=100.0

app.jwt.secret=Minha.chave.secreta


